name: build

# Controls when the action will run. Triggers the workflow manually or on push or pull request
on:
  workflow_dispatch:

  push:
    # Only run the workflow for pushes to the following files
    paths:
      - '.github/workflows/build.yml'
      - '**/*.js'
      - 'package.json'
      - 'package-lock.json'
    # Run on branches
    branches:
      - '**'
    # Don't run on tags
    tags:
      - '!**'
  pull_request:
    # Only run the workflow for requested changes to the following files
    paths:
      - '.github/workflows/build.yml'
      - '**/*.js'
      - 'package.json'
      - 'package-lock.json'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job will run pylint on all python files
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: latest
      - name: Install module
        run: npm install
      - name: Lint the code
        run: npm run lint

  # This job will run the tests
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: latest
      - name: Install module
        run: npm install
      - name: Test the code
        run: npm run test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
