name: release

# Controls when the action will run. Triggers the workflow on push to tags only.
on:
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "release" which publishes the javascript package
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Install dependencies
        run: npm install
      #- name: Publish package
      #  run: npm publish
      #  env:
      #    NPM_AUTH_TOKEN: ${{ secrets.NPM_JFROG_TOKEN }}
